# Generated by Django 6.0.4 on 2026-04-25 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('submit', 'Tool Submission'), ('download', 'File Download'), ('access_denied', 'Unauthorized Access Attempt')], max_length=20)),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ToolInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_slug', models.CharField(max_length=100)),
                ('tool_version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('payload_input', models.JSONField(default=dict, help_text='The raw user inputs.')),
                ('payload_output', models.JSONField(blank=True, default=dict, help_text="The tool's result.", null=True)),
                ('html_file', models.FileField(blank=True, null=True, upload_to='archives/html/')),
                ('md_file', models.FileField(blank=True, null=True, upload_to='archives/md/')),
                ('rtf_file', models.FileField(blank=True, null=True, upload_to='archives/rtf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_instances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
