# Generated by Django 6.0.4 on 2026-04-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_toolsession_md_file_toolsession_rtf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsession',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, help_text='Set when the host starts the phase timer so all clients stay in sync.', null=True),
        ),
    ]
