# Generated by Django 6.0.4 on 2026-04-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_timer_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsession',
            name='timer_elapsed_before_pause',
            field=models.FloatField(default=0, help_text='Cumulative elapsed seconds before the current (or last) pause.'),
        ),
        migrations.AddField(
            model_name='toolsession',
            name='timer_paused_at',
            field=models.DateTimeField(blank=True, help_text='Set when the host pauses the timer; cleared on resume or reset.', null=True),
        ),
    ]
