# Generated by Django 6.0.4 on 2026-04-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_timer_paused_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional — filled in voluntarily by the visitor.', max_length=200)),
                ('signed_up_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Waiting list entry',
                'verbose_name_plural': 'Waiting list entries',
                'ordering': ['-signed_up_at'],
            },
        ),
    ]
