# Generated by Django 6.0.4 on 2026-04-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_waiting_list_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsession',
            name='pause_reminder_threshold_sec',
            field=models.IntegerField(blank=True, default=300, help_text='How many seconds of pause before a long-pause reminder appears. Null disables the reminder entirely. Default is 300 (5 minutes).', null=True),
        ),
    ]
