# Generated by Django 6.0.4 on 2026-04-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_add_pause_reminder_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional — filled in voluntarily by the visitor.', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Optional — so they can be notified when the feature ships.', max_length=254)),
                ('title', models.CharField(help_text='A short summary of the feature being requested.', max_length=300)),
                ('description', models.TextField(help_text='More detail: what problem does it solve, how would it work?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feature request',
                'verbose_name_plural': 'Feature requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
